### ISSUE TITLE
ESM error in v4

### ISSUE THREAD

**Issue by yosbelms** [sindresorhus/p-defer#7]
I get the following error when using `p-defer@4.0.0`. The error is explicit, and offers 2 possible solutions.

```
Error: Must use import to load ES Module: /home/yosbel/Documents/experiments/procplay/node_modules/p-defer/index.js
require() of ES modules is not supported.
require() of /home/yosbel/Documents/experiments/procplay/node_modules/p-defer/index.js from /home/yosbel/Documents/experiments/procplay/.next/server/pages/_app.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/yosbel/Documents/experiments/procplay/node_modules/p-defer/package.json.
```

**Comment by sindresorhus** [comment]
Please read the release notes.

**Comment by joepie91** [comment]
Running into the same issue here.

Unfortunately [the instructions](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) in the release notes effectively boil down to "use ESM instead of CommonJS" (the other two not being maintainable options), which is not an option for me as its a strictly inferior module syntax - as synchronous imports are now a special-cased statement rather than a first-class expression, it has become impossible to ergonomically implement patterns like parametric modules, which poses a significant maintainability issue. There are also [many other issues](https://twitter.com/joepie91/status/1254368447250694146).

I guess I just won't be able to use any of your modules anymore? It seems like a strange decision to intentionally break compatibility with many people's existing codebases (presumably the older branches won't get future updates), when it isn't actually necessary for any technical reason - your modules worked fine in both CommonJS *and* ESM environments when they were CommonJS exports.
